#!/bin/zsh

# Borrowed from grunt-cli
# http://gruntjs.com/
#
# Copyright (c) 2012 Tyler Kellen, contributors
# Licensed under the MIT license.
# https://github.com/gruntjs/grunt/blob/master/LICENSE-MIT

# Usage:
#
# To enable zsh <tab> completion for maf, add the following line (minus the
# leading #, which is the zsh comment character) to your ~/.zshrc file:
#
# eval "$(maf --completion=zsh)"

# Enable zsh autocompletion.
function _maf_completion() {
  # Grab tasks
  compls=$(maf --tasks-simple)
  completions=(${=compls})
  compadd -- $completions
}

compdef _maf_completion maf
